### ISSUE TITLE
Update nag refuses to go away

### ISSUE THREAD

**Issue by TheDiscordian** [ipfs/ipfs-desktop#1847]
- OS: Windows
 - 0.15.0

**Describe the bug**
Getting update nag, informs user to restart application to resolve. Upon restart, nag returns.

**To Reproduce**
Run 0.15.0, have application detect there's a new update.

**Expected behavior**
Upon restart new version is installed, old version gone, update nag gone.

**Screenshots**

![Update nag](https://matrix.thedisco.zone/_matrix/media/r0/download/halogen.city/1d071fbb15d7a373316b086342b6eb2afe0b47ec)

**Additional context**

Reported to me by owocean: https://matrix.to/#/!gWiVYCURkxIapWZaGy:ipfs.io/$gMh0L6gUyOGnCVWGRL3Z7_9lBZfNwEk9spkpaxPO9w4?via=ipfs.io&via=matrix.org&via=privacytools.io

[combined.log](https://github.com/ipfs/ipfs-desktop/files/6682791/combined.log)
[error.log](https://github.com/ipfs/ipfs-desktop/files/6682792/error.log)

**Comment by lidel** [comment]
I was not able to reproduce this: installed 0.15.0 on a single user, started ipfs desktop, clicked "Check for updates", got the update notification, it got installed, Quit app, started again, 0.15.1 runs as expected.

**Comment by owocean** [comment]
Not once did I run "Check for updates"
This all happened automatically.

**Comment by lidel** [comment]
Hm.. still not able to replicate. I cleaned  `C:\\{your-user-name}\AppData\...\IPFS Desktop` and let v0.15.0 run until it picked up v0.15.1 and the update was smooth – after quitting, the  new version installed and run ok.

You had some network error related to update checks as well (`Error: net::ERR_FAILED|ERR_NAME_NOT_RESOLVED`), which gave me an idea: perhaps there is a problem with an update file present on your machine (corrupted file/disk)?

@owocean  are you able to replicate yourself?
1. Uninstall IPFS Desktop
2. Manually remove  `C:\\{your-user-name}\AppData\Roaming\IPFS Desktop`  (it is not removed by uninstall, but might include corrupted updates or some stale config)
3. Install [IPFS-Desktop-Setup-0.15.0.exe](https://github.com/ipfs/ipfs-desktop/releases/download/v0.15.0/IPFS-Desktop-Setup-0.15.0.exe) in single user mode ("only this user") and wait until it picks up the update, and see if the issue comes back.

**Comment by TheDiscordian** [comment]
> @TheDiscordian @owocean any thoughts on how to reproduce this? Any detail would be useful.

Unfortunately I don't experience this on Linux. I was hoping the report and logs would help uncover what went wrong.

**Comment by lidel** [comment]
This is a recurring problem with electron autoupdates.
Similar issue was recently fixed on macOS: https://github.com/ipfs/ipfs-desktop/issues/1980

:point_right: If anyone experiences this type of problem – apply a one-time manual update by installing  a package from [the latest release](https://github.com/ipfs/ipfs-desktop/releases/latest).
