### ISSUE TITLE
From where it assumes the user home path?

### ISSUE THREAD

**Issue by danimesq** [ipfs/ipfs-desktop#1935]
/home/.ipfs-desktop/IPFS_PATH is assigning a wrong username every time I start IPFS Desktop

Probably this bug affects from version 13 (or bellow) to the latest 17

**Comment by lidel** [comment]
Looks odd: `/home/.ipfs-desktop/` is missing user name.

What are your `$USER` and  `$HOME` in `env` used when running `ipfs-desktop`?

**Comment by danimesq** [comment]
> Your path looks odd: /home/.ipfs-desktop/ is missing username(?)

Sorry, I told here an sample non-absolute path.

> What are your $USER and $HOME in env used when running ipfs-desktop?

> 
> ❯ echo "$USER"
> daniella
> 
> ❯ echo "$HOME"
> /home/daniella

However, every time I openned IPFS Desktop, it overwrote /home/daniella/.ipfs-desktop/IPFS_PATH's content to /home/daniell/(something).
Seems like IPFS Desktop got it from some place, because my home folder is imported from my previous username which was "daniell"; is IPFS Desktop assuming this old username elsewhere?

**Comment by danimesq** [comment]
Possibly similar to https://github.com/ipfs/ipfs-desktop/issues/1749?

Because this issue also made my IPFS Desktop unusable despite `/usr/bin/ipfs` running its daemon and UI accessible from browser.

**Comment by danimesq** [comment]
There's already the detailed info.

**Comment by hacdias** [comment]
@danimesq hi! Even though there is an underlying issue here, the feature that uses `~/.ipfs-desktop/IPFS_PATH`, i.e., IPFS on PATH, is [deprecated](https://github.com/ipfs/ipfs-desktop/pull/1768) and only active if you've had it activated before. To disable it, click on the IPFS Desktop menubar icon, then **Preferences** and finally on **Command Line Tools**.

Regarding the value that is written to that file, it can be [found on](https://github.com/ipfs/ipfs-desktop#where-are-my-ipfs-configuration-and-log-files): `~/.config/IPFS Desktop/config.json` > ipfsConfig > path. If you change the value there to the new username PATH, it should be fixed.

Either way, I would recommend you to simply disable this feature altogether due to the reasons mentioned [here](https://github.com/ipfs/ipfs-desktop/pull/1768).
