### ISSUE TITLE
[gui error report] Error: Initializing daemon...

### ISSUE THREAD

**Issue by ckevinroque** [ipfs/ipfs-desktop#2023]
👉️ Please describe what you were doing when this error happened.

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.1
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
Error: Initializing daemon...
go-ipfs version: 0.12.0
Repo version: 12
System version: amd64/windows
Golang version: go1.16.12
Found outdated fs-repo, migrations need to be run.
Looking for suitable migration binaries.
Need 1 migrations, downloading.
Downloading migration: fs-repo-11-to-12...
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions"
Error fetching: exceeded number of retries. last error was http.DefaultClient.Do error: Get "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/versions": dial tcp: lookup ipfs.io: no such host
Fetching with IPFS: "fs-repo-11-to-12/versions"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1XayZCcxWZzKAHNVN/fs-repo-11-to-12/v1.0.2/fs-repo-11-to-12_v1.0.2_windows-amd64.zip"
Fetching with HTTP: "https://ipfs.io/ipfs/QmdaCHYBDHEhXCMoynH5UcohEay6m1X

**Comment by lidel** [comment]
It seems we are failing HTTP and then retrying with IPFS when fetching `/versions` and then  try to fetch actual file over HTTP again.

The error message is cut, so it is hard to tell if this failed due to real error or is a false-negative, but base don similar reports from https://github.com/ipfs/ipfs-desktop/issues/2018 and https://github.com/ipfs/ipfs-desktop/issues/2027 i think it is a racy bug in error handling logic.  We should:

-  ensure the last two lines are always sent with error report like this one
- avoid string matching, and have a catch-all error handling that engages when go-ipfs daemon pid points at dead/missing process

@ckevinroque are you able to attach your `combined.log` and `error.log`?
