### ISSUE TITLE
Hosting files on local node, but 404 error

### ISSUE THREAD

**Issue by StaticDave** [ipfs/ipfs-desktop#2029]
Windows 11 running IPFS Desktop v2.15.0

**Describe the bug**
I have been adding files/folders to my local node for some testing. Everything was working fine, but when I restarted the desktop it wouldn't load anything. Now when I try to even look at files, I get a "404" error and my import button is greyed out so I can't even add new files. I've waited for extended periods to see if it took time loading, to no avail. My system says I am hosting 30GB of files and blocks but it cannot seem to access/display them. I can view the node via explore, but I get a 404 error locally. How can i force reconnect desktop to my local node so I can continue with my project?

The error log is empty, so I'm not sure what is causing this.

Any ideas?

**Comment by StaticDave** [comment]
Thanks for the reply. After I clear the console and open files I am not getting any errors.

I *believe* after digging around that I somehow have a different peer ID than I did. I'm not sure how that could have happened, as I am using the same user profile on windows with the same IPFS that I made my files with.

Is there a way to change my peer ID?

**Comment by lidel** [comment]
@StaticDave you can change PeerID by doing `ipfs key rotate` in command-line, or by removing `.ipfs` (`IPFS_PATH`) from your system. Also, you may have more than one node running on your machine (e.g. if you are running both Brave and IPFS Desktop). I am closing as I understand your problems are solved (most likely due to purging broken  repo and starting anew). 


@Radderz81 please fill separate issue in https://github.com/ipfs/ipfs-companion/ repo.

**Comment by lidel** [comment]
Cool! Hopefully ipfs-dektop will be able to provide GUI to autofix such broken repos – we track that in https://github.com/ipfs/ipfs-desktop/issues/2050
