### ISSUE TITLE
ship with low power profile as default to reduce CPU usage

### ISSUE THREAD

**Issue by autonome** [ipfs/ipfs-desktop#2039]
**Is your feature request related to a problem? Please describe.**

I consistently see IPFS using ~5-11% CPU while I'm not interacting with it.

**Describe the solution you'd like**

Ship w/ low power profile as default.

**Describe alternatives you've considered**

Not running IPFS typically reduces the CPU usage to zero.

**Additional context**

Apparently humans are *not* 80% water. It's a myth.

**Comment by lidel** [comment]
We can't use lowpower profile because it would disable Reprovider which would break data providing.

The profile itself does very little:

https://github.com/ipfs/go-ipfs/blob/beaa8fc29b472214283b9aab884ed92f03908d13/config/profile.go#L177-L183

```go
			c.Routing.Type = "dhtclient"
			c.AutoNAT.ServiceMode = AutoNATServiceDisabled
			c.Reprovider.Interval = "0"

			c.Swarm.ConnMgr.LowWater = 20
			c.Swarm.ConnMgr.HighWater = 40
			c.Swarm.ConnMgr.GracePeriod = time.Minute.String()
```

The only thing we could tweak compared to the current settings is  to decrease ConnMgr values – i opened https://github.com/ipfs/ipfs-desktop/pull/2055

**Comment by lidel** [comment]
@autonome try updating to https://github.com/ipfs/ipfs-desktop/releases/tag/v0.20.4  – it uses lowpower `ConnMgr` settings, which should close unused connections faster. Less connections means less bitswap traffic, and that should improve CPU/bandwidth when  idle for more than 1m.
