### ISSUE TITLE
ipfs-webui crashing while trying to upload 53 Gb folder with subfolders

### ISSUE THREAD

**Issue by miguelgargallo** [ipfs/ipfs-desktop#2048]
👉️  Trying to upload 53 Gb folder with subfolders

**Specifications**

- **OS**: win32
- **IPFS Desktop Version**: 0.20.2
- **Electron Version**: 17.1.0
- **Chrome Version**: 98.0.4758.102

**Error**

```
TypeError: Object has been destroyed
    at Object.ctx.launchWebUI (C:\Users\mgarg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\webui\index.js:120:14)
    at EventEmitter.<anonymous> (C:\Users\mgarg\AppData\Local\Programs\IPFS Desktop\resources\app.asar\src\tray.js:277:37)
    at EventEmitter.emit (node:events:390:28)
```

**Comment by lidel** [comment]
@hacdias are you able to reproduce this on Windows?

**Comment by miguelgargallo** [comment]
WOW at that moment impossible I reset the computer! Sorry

**Comment by miguelgargallo** [comment]
My apologize, at that moment impossible I reset the computer! Sorry

**Comment by lidel** [comment]
@miguelgargallo I don't think the problem is caused by the data itself, but by the number of files and/or their total size.  We should be able to reproduce this with randomly generated fixtures, without revealing your private data. 

Are you able to give us some ballpark information how many files were in these 60GB? How deep the directory trees were?
