### ISSUE TITLE
Rename to Kubo-Desktop

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-desktop#2183]
Go-ipfs will be [renamed](https://github.com/ipfs/go-ipfs/issues/8959) to Kubo, and I think it would make sense to rename ipfs-desktop, too.

### Rationale

The idea behind the rename of go-ipfs was, to keep the "namespace" clean and allow other applications to refer to IPFS as a network, protocol, distributed storage – not as a specific application.

It's like Apache and Nginx are Servers for http(s), but there's no Server called go-http as reference implementation.

Following this argument, it makes sense to allow other applications to make desktop applications for ipfs without referring to this application.

**Comment by lidel** [comment]
The purpose of IPFS Desktop is to **bring IPFS features to desktop OS** (`ipfs://` and `ipns://` protocol handler, native file import, basic GUI for importing data and getting CIDs, automatic updates to the latest features) – **not to be a Kubo client**.


It happens to use Kubo (go-ipfs) right now, because it is the best implementation for the job. 
That may change in the near future, when we have an implementation tailored to the needs of desktop users.

**Comment by RubenKelevra** [comment]
So if not Kubo, maybe a different name could be discussed for the desktop client?

ipfs-desktop just feels super generic and I think a dedicated name would neat :)

**Comment by lidel** [comment]
Ideas welcome ;-) but..

- renaming is expensive, renaming desktop app will be _extremely_ expensive
- reasons for renaming Desktop application will be different from renaming go-ipfs
  - someone would have to demonstrate clear benefit to the end user, and assemble a team that drops everything and invests _weeks_ into another renaming process across docs, packages managers, courses, and user tutorials.

**Comment by RubenKelevra** [comment]
@lidel well, the desktop app shows now on the front page "kubo v0.14.0 desktop" as agent… well.

I still think it's worth changing applications away from the protocol name and make this "a good habit" to avoid confusing people.
