### ISSUE TITLE
ipfs Windows 客户端在重装系统后文件丢失

### ISSUE THREAD

**Issue by mzh688** [ipfs/ipfs-desktop#2231]
ipfs Windows 客户端好像不需要账号密码登录吧，因为C盘空间占用爆满就重新格式化了硬盘重做了Windows系统，（ipfs客户端在上传文件的时候C盘会占用大量空间，也不知道怎么选择别的盘）。重做完Windows系统后安装ipfs发现文件都没有了，节点ID好像也变了
---
Google translation: The ipfs Windows client does not seem to need an account and password to log in. Because the C drive is full, the hard disk is reformatted and the Windows system is redone. (The C drive will take up a lot of space when the ipfs client uploads files. I don’t know how choose another disk). After redoing the Windows system, I installed ipfs and found that the files are gone, and the node ID seems to have changed.

**Comment by mzh688** [comment]
还有，我希望ipfs windows客户端加入全中文操作。

**Comment by SgtPooki** [comment]
Thanks for opening an issue @mzh688. It sounds like there are two issues here: 

1. Your files are gone when your HDD is reformatted
   * You mention the lack of a user account with the IPFS Desktop application
   * You want to know how to change the location of your local ipfs repo
   * You want to know how to keep the peer ID of your node the same even after a restart
2. The Chinese translations are not entirely done

---

**For the first issue**, this is expected behavior. If you want to persist files you have in IPFS, you will need to use a pinning service, or a persistent machine running ipfs. You can read more about [persisting files](https://docs.ipfs.tech/concepts/persistence/) and [pinning](https://docs.ipfs.tech/how-to/pin-files/) on our [ipfs docs site](https://docs.ipfs.tech/). The different pinning services (Pinata, Estuary, web3.storage, nft.storage, crust, etc..) may have user accounts.

For changing your local ipfs repo, see https://github.com/ipfs/ipfs-desktop#how-does-ipfs-desktop-select-the-ipfs-repo-location

For persisting your peer ID, you may want to read up more on how [peer IDs are generated](https://discuss.libp2p.io/t/generating-peer-id/111/5). If your HDD is reformated, any key created by ipfs would have been deleted, resulting in ipfs generating a new key on initilization, and ultimately a completely new and different Peer ID. After understanding how they're generated, check out https://docs.ipfs.tech/how-to/use-existing-private-key/ for how you can import your own key(s) so that a new instance of ipfs will result in the same Peer ID.


**For the second issue**, if you notice some translations that are missing or incorrect, we would love it if you could help. We use Transifex for translating English to other languages. See https://github.com/ipfs/ipfs-desktop#translations for more information

**Comment by mzh688** [comment]
谢谢你的完美解答，我已经大致了解了我的问题如何解决。我会去按照你给的参考文献去学习如何使用，并帮助身边的朋友去学习。非常感谢！

**Comment by mzh688** [comment]
@SgtPooki  谢谢你的完美解答，我已经大致了解了我的问题如何解决。我会去按照你给的参考文献去学习如何使用，并帮助身边的朋友去学习。非常感谢！
