### ISSUE TITLE
ipfs-desktop on Windows always errors, never starts ipfs on login

### ISSUE THREAD

**Issue by IngwiePhoenix** [ipfs/ipfs-desktop#2232]
- OS: Windows 10
- Version of IPFS Deskop: 0.22

**Describe the bug**
I have had the IPFS Desktop installed for a while, and was wondering how I could make it start IPFS on login. Turns out that this is supposed to be an actual feature. Well, it never worked unless I manually started the daemon. Meaning, that IPFS Desktop on my Windows maschine has thus far never brought up IPFS itself ever.

**To Reproduce**
I honestly wish I knew what led to this bug. All I did was to install it via Chocolatey and whilst installing an update, I selected "Only for myself".

**Expected behavior**
I expected to have an IPFS node running whenever I log into my Windows.

**Screenshots**
None, except the "IPFS has errored" message.

**Additional context**
None that comes to mind.

[error.log](https://github.com/ipfs/ipfs-desktop/files/9390034/error.log)

**Comment by SgtPooki** [comment]
@IngwiePhoenix Thanks for bringing this to our attention. Could you also attach the `combined.log` file?

It looks like you're on the latest version of IPFS desktop, so that's great. However, it sounds like you're saying that when you start IPFS Desktop, you have to start the ipfs daemon manually, or is it that you need to start the IPFS Desktop application manually?

IPFS Desktop is supposed to enable launch on startup automatically, as you can see at https://github.com/ipfs/ipfs-desktop/blob/e16b1e7374b0d614c4bd2416b7b75cd58f45d85e/src/auto-launch.js#L86. We should be able to see what's happening once we get your `combined.log` file.

Is IPFS Desktop listed as a startup app? Could you share a screenshot showing as much? Or you could provide the full terminal output of running either of the below commands:

**Windows cmd/batch**
```
wmic startup get caption,command
```

**Powershell**
```
Get-CimInstance Win32_StartupCommand | Select-Object Name, command, Location, User | Format-List 
```

If IPFS Desktop is not listed there, you may need to add it to your list of startup applications manually for now.

**Comment by SgtPooki** [comment]
Thanks for providing the combined.log. It looks like [this code](https://github.com/ipfs/ipfs-desktop/blob/e16b1e7374b0d614c4bd2416b7b75cd58f45d85e/src/auto-launch.js#L84-L86) is being called multiple times, which means the configuration isn't being saved properly. We will need to investigate this further.


### Steps to troubleshoot:
* Try to restart desktop
   * Is IPFS-desktop failing to run the daemon only during startup, or all the time?
* Start binary for daemon that is bundled with IPFS-Desktop manually using CLI
   * `C:/Windows/Users/$user/AppData/Local/Programs/IPFS Desktop/` should contain the binaries (file locations are called out here: https://github.com/ipfs/ipfs-desktop/issues/1656#issuecomment-704979096) 
   * Can you manually start the exact binary that IPFS-Desktop uses and cannot start?

**Comment by SgtPooki** [comment]
@IngwiePhoenix we don't have the bandwidth to investigate this further at this moment but if you can provide further information so it can be looked into when someone has time that would be very helpful.
