### ISSUE TITLE
IPFS desktop should have a download/upload management/logging screen

### ISSUE THREAD

**Issue by hollownights** [ipfs/ipfs-desktop#2390]
Much like any BitTorrent client’s UI has at its center, IPFS desktop should also have a download/upload management/logging screen. This would allow:

1) better storage and bandwidth control, as the user would easily know what is actually being downloaded/uploaded;
2) managing transmissions by pausing/starting them;
3) better debugging, cause, right now, there is no way to know why a file isn’t being downloaded/uploaded (you can’t know why if you don’t even know if it is doing anything).

Due to IPFS’ nature, this screen could (should?) be a little different to its BitTorrent counterpart and only show active downloads/uploads and downloads/uploads made in the last X hours, and not all downloads/uploads ever made.

**Comment by ShadowJonathan** [comment]
IPFS is more loose about uploading files than bittorrent, whereas bittorrent deals with streams of specific files, IPFS uses something called "bitswap", which is simply a list of blocks (from any file) that it wishes to have, and the local client can lookup if it has that block, and give it.

Due to the nature of IPFS pins, and with how much is cached locally when some user is simply browsing, it's not really easily possible to resolve (quickly) what "file" a user is uploading to a specific user. It's easier to understand on the receiving end to see how far the file upload is, with something like https://github.com/ipfs/ipfs-desktop/issues/2386.

Kubo (the underlying IPFS implementation of ipfs-desktop) could have better bandwidth controls though, and there i completely agree, but the other requests are harder to work out. I believe some of these issues can be broadly addressed once a bandwidth limiter arrives to kubo, together with a progress bar on the receiving end.
