### ISSUE TITLE
run garbage collector problem

### ISSUE THREAD

**Issue by Phrixus2023** [ipfs/ipfs-desktop#2745]
![微信截图_20240203151542](https://github.com/ipfs/ipfs-desktop/assets/142395052/59a0f8b1-6b3b-4435-a46d-5d5045bf2690)
When I clean up the cached block file, there is a situation that the imported file is lost, but the total size of the file and the block capacity are shown, but I can't continue to import the file, I would like to ask how to deal with this situation.

**Comment by lidel** [comment]
Total size is likely correct, because you still have data in your repository.

You can trigger garbage-collection of cached blocks via tray menu:

> ![image](https://github.com/user-attachments/assets/ff010cbd-886d-43da-8070-0ab49341a8f4)

If the number does not go down after GC finishes running, you may want to use [Kubo CLI](https://docs.ipfs.tech/reference/kubo/cli/) to see if you have low-level pins.

ps. In future, for user support please reach out to forums at https://discuss.ipfs.tech/c/help/13
