### ISSUE TITLE
Importing by CID is not working

### ISSUE THREAD

**Issue by HaveANiceDaySir** [ipfs/ipfs-desktop#2755]
So I've tried running my own node as an alternative to pinning services like Pinata. However, I'm having several issues from pinning my files through IPFS Desktop, I try to import using the CID already used for files, but it just won't load them even if they are 200 KB in size.
I'm running IPFS Desktop on Windows 11. I haven't changed anything on the configuration, so that should be the default one.
Is there a way to force the pin of my file, maybe through the command line?

**Comment by HaveANiceDaySir** [comment]
Following up on this, I have found that the IPFS Desktop gets stuck when trying to pin SVG files specifically, the only way I have found to properly pin the is by forcing a lot of files through the Import button to be pinned. It does take a while, but it will pin them. However, it won't pin them if I just do it once.
![image](https://github.com/ipfs/ipfs-desktop/assets/142706814/f60c126d-201c-43e5-abe8-f62e2280d2f0)

**Comment by lidel** [comment]
@HaveANiceDaySir apologies for slow reply. This seems to be a problem specific to a CID you are trying to import into your local node.

Make sure it has a publicly diallable provider. 
You can check providers via `https://delegated-ipfs.dev/routing/v1/providers/CID` 

Example: https://delegated-ipfs.dev/routing/v1/providers/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi 

There is also https://check.ipfs.network/ which allows you to probe provider from remote node, to know if the problem is your machine, or the provider.

If you need further support, please open topic at https://discuss.ipfs.tech/c/help/13, this issue tracker is about bugs in Desktop app specifically.
